spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      
  rabbitmq:
    host: localhost
    port: 5672
    username: kopic
    password: kopic123

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus,shutdown